splitgraph/seafowl

seafowl.toml
src/context.rs
src/frontend/http.rs
src/nodes.rs
src/wasm_udf/data_types.rs

Some more implementation for https://github.com/splitgraph/seafowl/issues/20 and other fixes:
- add CORS
- add optional `.extension` to `GET /q/hash[.extension` (ignored by us, but used by Cloudflare to see if it's a cacheable asset)
- add support for query in the `GET` body
- add `POST /q` to execute uncached RW queries (no authz until https://github.com/splitgraph/seafowl/issues/11)
- replace mock context with in-memory SQLite (does mean we end up relying on some parts of the context's implementation but is much more concise than using mocks)
- simplify some routing/parsing

HTTP API implementation

---

src/context.rs
src/frontend/http.rs

This addresses the issue #40, by providing a POST endpoint `/upload/[schema]/[table]`, whereby the provided file contents are parsed and used to create/append to table.

Implement CSV/Parquet upload endpoint

---

src/auth.rs
src/config/context.rs
src/config/schema.rs
src/context.rs
src/frontend/http.rs
src/frontend/http_utils.rs
src/frontend/mod.rs
src/lib.rs
tests/http.rs

- See `src/frontend/http_utils.rs` for errors that are now raised/returned
- See `src/auth.rs` for the auth policy (which now matches https://www.splitgraph.com/docs/seafowl/reference/seafowl-toml-configuration#frontendhttp-section)

Add V0 AuthZ and basic HTTP error handling

---

src/config/schema.rs
src/frontend/http.rs
src/main.rs

- Set logging to INFO by default (except for sqlx which logs too much at INFO, so downgrade it to WARN)
- users can override logging using the `RUST_LOG` envvar (https://docs.rs/env_logger/latest/env_logger/#enabling-logging)
- Log warp access at INFO level (things like `2022-08-17T10:43:40.224Z INFO  seafowl::frontend::http > 127.0.0.1:55508 "OPTIONS /q/ HTTP/1.1" 405 "-" "curl/7.68.0" 98.455µs`)
- Generate a default config and output it to `seafowl.toml` on first run / if it doesn't exist
- Add `access-control-max-age: 86400` to CORS preflights so that they're cached by the browser for more than 5 seconds

CLI niceties

---

.github/workflows/nightly.yml
Cargo.toml
README.md
build.rs
src/config/schema.rs
src/main.rs

Closes https://github.com/splitgraph/seafowl/issues/46
Partially relates to https://github.com/splitgraph/seafowl/issues/45 (yes compile, no release)
Use https://crates.io/crates/vergen to add some basic build info to the Seafowl binary:
```bash
$ ./seafowl -V
Seafowl 0.1.0 (aa8c19cbc54c612733068b3c497f61cbb57905fe 2022-08-17T16:56:40Z)
Built by rustc 1.63.0 on x86_64-unknown-linux-gnu at 2022-08-17T16:57:27.702859916Z
Target: release x86_64-unknown-linux-gnu
Features: catalog_postgres,convergence,convergence_arrow,default,frontend_postgres,object_store_s3
```
Add GHA release builds (OSX, Linux, Windows) for pushes to the main branch, available as GHA artifacts to logged-in users or on https://nightly.link: https://nightly.link/splitgraph/seafowl/workflows/nightly/feature%2Fauto-binary-ver …

Add binary version info and nightly release builds

---

src/lib.rs
src/main.rs
src/utils.rs

Fixes https://github.com/splitgraph/seafowl/issues/39
Supports multiple commands but hackily (splits on `;`).

Add ability to run a one-off command from the CLI

---

Cargo.toml
src/catalog.rs
src/config/context.rs
src/context.rs
src/frontend/http.rs
src/frontend/http_utils.rs
src/frontend/postgres.rs
src/main.rs
src/provider.rs
src/repository/default.rs
src/repository/interface.rs
src/repository/postgres.rs
src/repository/sqlite.rs
tests/end_to_end.rs
tests/http.rs

Fixes #22 
Fixes #53 
- Add code for converting PG/SQLite errors into certain generic DB errors (FK/Unique violation): sqlx doesn't do that already for us, maybe we should have used an orm 👀 
- Define an error type for catalog-specific errors (e.g. table/schema/database doesn't exist/already exists)
- Add some logic in the catalog that converts from DB errors to catalog errors (remove unwrap()s)
- Handle and propagate Warp errors in the upload endpoint to HTTP errors
- Propagate errors as DataFusion errors:
- X doesn't exist: internal error (these functions are only called by ID and the user only references tables by their name, so wrong IDs means something has gone wrong internally)
- X already exists: user-level error (target for a table rename / create function already exists)
- other …

Remove most unwrap()s and propagate errors up to the caller

---

src/config/schema.rs
tests/end_to_end.rs
tests/http.rs

Use e.g. `SEAFOWL__FRONTEND__HTTP__WRITE_ACCESS` as an envvar to
partially override the config.

Add envvar config parsing

---

migrations/postgres/20220705072248_create_tables.up.sql
migrations/sqlite/20220728071524_create_tables.sql
src/catalog.rs
src/context.rs
src/lib.rs
src/provider.rs
src/repository/default.rs
src/repository/interface.rs
tests/end_to_end.rs

Instead of defaulting to scanning all of the partitions, the goal here is to use the statistical summary for each column in each partition, and based on the filter/qualifier used in the query determine whether some of the partitions are superfluous for getting a correct result. If this determination succeeds simply scope the scan down only to partitions which are relevant to the query.

Implement min/max/null-count partition pruning

---

src/config/context.rs
src/config/schema.rs
src/frontend/http.rs
tests/http.rs

In order to circumvent the default max form data length of 2MB, we need to have this property configurable. For now, make it default to 256 MB.

Make upload endpoint max data length configurable

---

.github/workflows/ci.yml
Cargo.toml
src/context.rs
src/provider.rs

Instead of using the string as an intermediary for persisting min/max partition stats, use Datafusion protobufs, which are more adequate for serde into a DB. One big benefit is that Timestamp* types get to keep the timezone info after a round trip, and can therefore be used for partition pruning.

Serialise min/max partition stats into protobufs

---

Cargo.lock
Cargo.toml
src/context.rs
src/lib.rs
tests/http.rs

Instead of loading up the entire file into memory and uploading it in one big chunk, perform a multipart upload of small buffered file chunks.

Implement multipart partition object upload

---

Cargo.lock
Cargo.toml
src/context.rs
src/datafusion/parser.rs
src/frontend/http.rs
tests/end_to_end.rs

Also fixes https://github.com/splitgraph/seafowl/issues/112 and upgrades to object_store 0.5.0.

Upgrade DataFusion to 12

---

Cargo.lock
src/catalog.rs
src/context.rs
src/nodes.rs
src/provider.rs
src/repository/default.rs
src/repository/interface.rs
tests/end_to_end.rs

The present `DELETE` implementation is based on the fine-grained approach, whereby we utilize pruning to pinpoint which partitions will need elements removed. We then scan + filter from these partitions only (batching adjacent ones together to minimize sparse partition number) creating new substitute partitions, while re-using the ones unaffected by the `WHERE` qualifier of the `DELETE` from the old table version as is.

Add delete statement support

---

Cargo.lock
Cargo.toml
src/frontend/http.rs
src/frontend/http_utils.rs

headers cannot contain special characters such as newlines (as is described in GH issue #104). The solution is to percent-encode (aka: encodeURIComponent()) the query string. Encoding is not mandatory, some characters like the space are HTTP header-safe, these characters can be sent both as they are or percent encoded (e.g. %20 for space).

Percent-decode incoming queries

---

src/context.rs
src/datafusion/utils.rs
src/nodes.rs
src/provider.rs
src/utils.rs
tests/end_to_end.rs

Implementation of `UPDATE` statement in Seafowl, along similar lines as `DELETE`.
Basically, we pinpoint the exact partitions that need to be updated, and then for the new table version we do a projection of all columns that were changed using the provided assignment expressions. If a WHERE qualifier has been used, we further wrap up the assignment expressions using a CASE expression, to scope down the changes only to affected rows. The columns which were not changed are just projected as is.

Add update statement support

---

src/catalog.rs
src/context.rs
src/lib.rs
src/provider.rs
src/repository/default.rs
src/repository/interface.rs
src/system_tables.rs
src/version.rs
tests/end_to_end.rs

Implement a new systems schema, allowing for adding custom view-like tables that will query our metadata store and provide relevant insight to the users. The first example introduced here is `table_versions` table, which can be used to browse the available table versions and their creation timestamps.

System schema and table version table

---

src/config/context.rs

With one partition (the default if `num_cpus=1`), we seem to hit some DataFusion bugs:
- https://github.com/splitgraph/seafowl/issues/186
- potentially https://github.com/splitgraph/seafowl/issues/185
As a temporary workaround, pretend we always need at least 2 partitions, which makes DataFusion use alternative query plans.

Use a minimum of 2 `target_partitions`.

---

Cargo.lock
Cargo.toml
ci/clippy.sh
src/nodes.rs
src/repository/default.rs
tests/end_to_end.rs

Multiple partition IDs can have the same object storage IDs (which can happen if we produced two tables with contents that hash to the same ID). We want to select only those object storage IDs that are not used by any partition that's linked to any table.
For example:
```
physical_partition: (partition_1, object_1), (partition_2, object_1)
table_partition: (id_1, partition_1)
```
Currently, we just select object IDs where partition IDs are not in table_partition. This means we'll mistakenly delete object_1. We need to first build a set of all objects used by at least one partition, then subtract that from the set of all objects.

Fix `VACUUM PARTITIONS` with multiple tables (same contents)

---

src/context.rs
tests/end_to_end.rs

When processing a `DELETE` statement, we use `WHERE` clause to see which partitions to scan through (vs copy directly to the new table version, since they're definitely unaffected by the `DELETE`). Then, we construct a scan through the remaining partitions that only keeps the rows that would remain after the `DELETE`.
However, we invert the `WHERE` clause only in the filter expression, not the `scan_filters` that go into the Parquet file reader. This means that the Parquet file reader will discard partitions that definitely don't need to be deleted (as opposed to discarding partitions that definitely don't need to be kept).

Fix `DELETE` filter plan logic with string filters

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
ci/clippy.sh
src/context.rs
src/datafusion/parser.rs
src/frontend/http.rs
src/lib.rs
src/nodes.rs
src/object_store/cache.rs
src/remote_tables.rs
src/system_tables.rs
tests/end_to_end.rs

This PR introduces a new remote table concept, analogous to FDWs in Postgres, that uses the [connector-x](https://github.com/sfu-db/connector-x) lib to query a supported remote database.
- The implementation builds on the external table DF concept, and extends/abuses the syntax to provide the user with capability to specify the remote table (schema and) name, as well as the connection string for the remote database. 
- It also uses the staging schema for storing the remote tables in an ephemeral manner for now.
- The remote tables themselves support schema introspection, so the user is not obliged to supply it in the table definition. On the other hand, if the user does supply it and we determine a mismatch of a field datatype, the implementation will perform the necessary casting so that …

Remote table implementation

---

Cargo.lock
Cargo.toml
src/remote_tables.rs
tests/statements/ddl.rs
tests/statements/dml.rs
tests/statements/function.rs
tests/statements/mod.rs
tests/statements/query.rs
tests/statements/vacuum.rs

Use custom connector-x version with bumped rusqlite that allows for using the sqlite source aligned with our sqlx crate version.
Use the [AnyPool](https://github.com/launchbadge/sqlx/blob/054f61980a13716844bc9f90bf135b887a5a0fdb/src/lib.rs#L47) abstraction for seeding the remote DB in the tests.

Enable SQLite remote tables

---

src/remote_tables.rs
tests/statements/query.rs

Given that we already apply to supplied projection when fetching remote table data there's no need to set it in the MemoryExec plan as well, otherwise we try to project from the projected schema, which usually end with out of bounds indices
```bash
$ curl -H "Content-Type: application/json" localhost:8080/q -d'{"query": "SELECT * FROM staging.table_1"}'
{"a":1,"b":1.1,"c":"one","date field":"2022-11-01","e":"2022-11-01"}
{"a":2,"b":2.22,"c":"two","date field":"2022-11-02","e":"2022-11-02"}
$ curl -H "Content-Type: application/json" localhost:8080/q -d'{"query": "SELECT \"date field\", b FROM staging.table_1 WHERE a > 1"}'
Arrow error: Schema error: project index 3 out of bounds, max field 3
```

Fix remote table projection bug

---

.github/workflows/ci.yml
src/remote_tables.rs
tests/statements/query.rs

Siply add the LIMIT clause to the remote query if present

Pushdown LIMIT when querying remote tables

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
datafusion_remote_tables/Cargo.toml
datafusion_remote_tables/README.md
datafusion_remote_tables/src/filter_pushdown.rs
datafusion_remote_tables/src/lib.rs
datafusion_remote_tables/src/provider.rs
src/context.rs
src/lib.rs
src/remote_tables/mod.rs

Refactor the repo so that the remote table logic is extracted into a self-contained crate, with seafowl being the root package of the [workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#root-package).
To run all the test use `cargo test --workspace` (or target a specific package with `-p`); `fmt` will fix code in the (sub)crate as well, while existing CI tomlfmt should also fix its Cargo.toml.
Closes #237.

Factour out remote tables into a separate crate

---

datafusion_remote_tables/README.md
datafusion_remote_tables/src/factory.rs
datafusion_remote_tables/src/lib.rs
src/config/context.rs
src/context.rs
src/datafusion/parser.rs
src/nodes.rs
tests/statements/query.rs

This employs DataFusion's new external table creation logic, so that conditional on registering the remote table factory during runtime, anyone can use the plain `CREATE EXTERNAL TABLE` statement without having to rely on custom/parsing hacks (such as smuggling the table name via the `file_compression_type` field that we used to do).

Implement remote table factory

---

src/config/context.rs
src/config/schema.rs
src/object_store/cache.rs

`AmazonS3Builder` does not infer region properly from the endpoint URL, so we need to add a specific `region` field to the config. Both `region` and `endpoint` are now optional parameters (but at least one needs to be supplied).
The previous functionality is obtained by omitting the `region` param (usefull for targeting e.g. minio). Otherwise, if pointing directly to AWS S3, only `region` is sufficient since the endpoint is inferred automatically.
Closes #253

Add region config option for Amazon S3 store

---

src/context.rs
src/object_store/http.rs
src/wasm_udf/data_types.rs

There's a [nasty bug](https://github.com/apache/arrow-datafusion/blob/3cc607de4ce6e9e1fd537091e471858c62f58653/datafusion/sql/src/statement.rs#L167) in `datafusion-sql` which results in quoted collection and column names being parsed incorrectly (with the `"` character being considered part of the name).
During Splitgraph to Seafowl sync, the following SQL statements are run:
```sql
CREATE EXTERNAL TABLE tmp_hvlfgdshkjhnkbhy STORED AS PARQUET LOCATION 'https://storage.googleapis.com/jruw973mdb/p.parquet';
CREATE TABLE tmp_hvlfgdshkjhnkbhy AS SELECT * FROM staging.tmp_hvlfgdshkjhnkbhy;
CREATE SCHEMA "neumarktest/seafowlsync";
ALTER TABLE tmp_hvlfgdshkjhnkbhy RENAME TO "neumarktest/seafowlsync"."table1";
```
This MR requires to absolute minimum required to enable the query above to run. …

Minimal fix for unquote bug for DataFusion 15.0

---

src/config/context.rs
src/config/schema.rs
src/context.rs
src/object_store/cache.rs
src/object_store/http.rs

To set a custom root CA for TLS, use eg:
```bash
SEAFOWL__MISC__SSL_CERT_FILE=rootCA.pem ./target/debug/seafowl -c seafowl.toml
```
or in `seafowl.toml` add:
```toml
[misc]
ssl_cert_file="rootCA.pem"
```

Move ssl_cert_file option into seafowl config

---

Cargo.lock
Cargo.toml
src/context.rs
src/datafusion/parser.rs
src/nodes.rs
src/provider.rs
tests/statements/dml.rs

Instead of using our custom extension nodes. This has some potential upsides, mostly revolving around leveraging the community development and support around the new `LogicalPlan::Dml` variants.
However, I'm not convinced that this is a proper thing to do right now. For one thing, `LogicalPlan::Dml` makes a specific interpretation for the INSERT, UPDATE and DELETE plans, which is that it simply projects the changed rows (deleted, updated), instead of all the resulting rows which makes natural sense for other plans. Arguably, this is good since the changes to the tables can be arbitrarily small so it makes more sense to only output the changes. Consequently though, we have to extract the effective assignment and selection expressions for our purposes (keeping in mind table versioning and …

Use native DML planning nodes for processing write statements 

---

.github/workflows/nightly.yml

Help reduce the risk of building a bad binary
1. After building the binary we perform a minimally viable invocation (e.g. `seafowl --version`) using each OS in the [matrix](https://github.com/splitgraph/seafowl/commit/fd6ebfdf3d835e1360a9dba770a26ab6acde689a). Serves as a basic smoke test to answer the Q "did it run?"
2. In case of non-zero exit code, pass it into the `exit` call. I've only observed macOS so far, which today returned `134` for the binary with the SSL issue.
Because I don't have a Windows machine immediately available to test on, I can't say for 100% sure. 😓 
My understanding is that because [bash](https://github.com/splitgraph/seafowl/commit/97a0a83e24f8eebf13073c347ac51f384ac351e0) is running across all three OSes, we can at least say the bash script ran because `act -n` …

Experimental: introduce a basic "did it run" test to the GHA

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Cargo.toml
src/catalog.rs
src/config/context.rs
src/context.rs
src/frontend/http.rs
src/frontend/postgres.rs
src/main.rs
src/repository/default.rs
src/repository/interface.rs
src/utils.rs
tests/http/mod.rs
tests/http/query.rs

Specifically, add support to scope down the session context to a particular database for a given statement/batch of statements. In other words cross-DB queries are not supported atm.  This is done by extending the existing GET & POST routes to also support the prefixed `/db-name/q[/query-hash]` form, and then effectively switch the default database to the one provided.
Also contains the implementation of `CREATE DATABASE` statement.
The upload endpoint needs to be altered as well, but I plan on doing it in a separate PR.
Closes #288.

Implement multi-DB support in Seafowl

---

src/frontend/http.rs
tests/http/upload.rs

This allows for targeting schemas/tables outside of the `default` DB.

Add multi db support to the upload endpoint

---

src/catalog.rs
src/context.rs
src/datafusion/parser.rs
src/nodes.rs
src/repository/default.rs
src/repository/interface.rs
tests/statements/mod.rs
tests/statements/query_legacy.rs
tests/statements/vacuum.rs

There's one caveat with the current implementation, though it's not a deal breaker IMO—when Delta files are deleted there's no API to determine which table versions are valid, so we delete all but the latest one in our catalog. This means there could be versions which are still working and can be queries via time-travel but are not listed in `system.table_versions`.

Enable `VACUUM` for Delta tables

---

Cargo.lock
datafusion_remote_tables/Cargo.toml
src/main.rs
src/object_store/cache.rs

The tokio runtime handle that is used to block on evicted value's corresponding file deletion needs to be created in a context of a Tokio runtime. 
If created in the eviction method itself it will silently panic with `there is no reactor running, must be called from the context of a Tokio 1.x runtime`, after which point no evictions will be attempted again (but everything will continue running). In turn this will eventually lead to `cached file path already exists` errors from #333, as the files are never cleaned up. 
Arguably, it may be preferable to either skip or overwrite an existing path instead of erroring out, but I've left it for now as it may help us flush out some other bugs.
Co-incidentally, this revealed a design problem with the cache, namely after we full up the cache …

Fix the silent panic in the cache eviction hook rendering it useless

---

src/config/context.rs
src/config/schema.rs
src/context.rs
src/object_store/cache.rs
src/object_store/http.rs
tests/statements/mod.rs

Also, enforce a TTL on the cache as a workaround for moka's eviction policy shortcomings for full caches:  https://github.com/moka-rs/moka/issues/147#issuecomment-1162899784
Closes #41.

Enable caching of S3 objects in the local FS

---

.github/workflows/nightly.yml

Also add a step to test invkoing the new docker image.
Closes #343.

Force build to run on Ubuntu 20.04 to evade libssl 3 for now

---

.history
Cargo.lock
Cargo.toml
datafusion_remote_tables/Cargo.toml
datafusion_remote_tables/src/filter_pushdown.rs
src/config/context.rs
src/context.rs
src/datafusion/parser.rs
src/datafusion/utils.rs
src/delta_rs/backports.rs
src/frontend/http.rs
src/main.rs
src/nodes.rs
src/object_store/http.rs
src/object_store/wrapped.rs
src/provider.rs
src/wasm_udf/data_types.rs
src/wasm_udf/wasm.rs
tests/statements/dml.rs
tests/statements/query.rs
tests/statements/vacuum.rs

Upgrade Seafowl to DF 22 and Arrow 36, and thereby close #349.
Also refine some finesse(s) on UPDATE and DELETE partition pruning logic, and add corresponding tests. In particular, in case when we don't have any partitions to remove/add to the table state (because the `WHERE` clause completely misses all partitions), simply make a new table version and inherit all partitions as is. There are two alternatives that could be done here:
- make a new table version and if there are more than 1 partition try to fuse them together.
- don't make a new table version at all.

Datafusion 22 upgrade

---

src/context.rs
tests/statements/ddl.rs

In particular, ensure these can include slash, dash and colon at least.
Closes #361.

Fix renaming table to schemas/tables with special characters

---

src/frontend/http.rs

This is in addition to the previously supported options of using the request body or a special `X-Seafowl-Query` header as mediums to send the query, but this particular approach is a bit more user-friendly (no need to calculate/supply the query hash).
Closes #55.

Enable passing query as a path parameter in the GET endpoint

---

src/config/context.rs
src/config/schema.rs
src/frontend/http.rs

Enable specifying the GET endpoint cache-control header via config

---

Cargo.lock
Cargo.toml
src/context.rs
src/frontend/http.rs
src/frontend/http_utils.rs

This is so as to avoid accumulating the entire result in memory and potentially OOM-ing the process. Closes #258
Example, using a large table to perform `SELECT * ... LIMIT 100000`:
- W/O streaming memory peaks at 220MB (current main)
- W/ streaming memory peaks at 30MB (this PR)

Implement streaming of result rows

---

docker-compose.yml
src/config/context.rs
src/context.rs
tests/statements/ddl.rs

The only thing that prevented us from employing the relevant DataFusion functions entirely was our custom `file_extension` setting for HTTP files/tables (to allow disabling filtering by an extension). Previously we copied a lot of code just to make that small change, but now it works as desired in DF, thanks to https://github.com/apache/arrow-datafusion/pull/6274.
Also add a test targeting minio as the host of the HTTP file.

Simplify the external table creation logic

---

.github/workflows/nightly.yml
Cargo.lock
Cargo.toml
src/context.rs
src/frontend/http.rs
src/frontend/http_utils.rs
tests/http/mod.rs
tests/http/upload.rs

Instead of buffering the entire file in memory, stream the incoming bits to a local temp file, and then scan it when appending to the target table.
Memory implications (using a [160MB parquet file](https://seafowl-public.s3.eu-west-1.amazonaws.com/tutorial/trase-supply-chains.parquet)):
- Load-file-in-memory approach (current state)
- With streaming to disk (this PR)
In addition, bump DataFussion to post-26 version to pick up [schema coercion in Parquet reader](https://github.com/apache/arrow-datafusion/pull/6458), and thus close #179. Also add some tests demonstrating the new flexibility of the upload endpoint (implicit type casting, column skipping etc.).

Upload endpoint refinements

---

.github/workflows/nightly.yml
Cargo.lock
src/catalog.rs
src/context.rs
src/frontend/http.rs
src/repository/default.rs
src/repository/interface.rs
tests/http/upload.rs

Previously those have been omitted.
Also when scoping to a new DB, double-check the missing ids with a hit to the catalog to pick up databases created on a different node.

Load schemas without any tables into context as well

---

.gitignore
Cargo.lock
Cargo.toml
README.md
src/cli/commands.rs
src/cli/helper.rs
src/cli/mod.rs
src/lib.rs
src/main.rs
tests/cli/basic.rs
tests/cli/mod.rs
tests/main.rs

Add a basic CLI implementation  that supports searchable history, multi-line comments and multi-statement queries:
```bash
gruuya@markogrujics-MacBook-Pro seafowl % cargo run -- --cli                                            
Compiling seafowl v0.5.2 (/Users/gruuya/Splitgraph/seafowl)
Finished dev [unoptimized + debuginfo] target(s) in 5.06s
Running `target/debug/seafowl --cli`
default> create table t as values (1, 'one'), (2, 'two');
Error during planning: Table "t" already exists
default> drop table t;
Time: 0.006s
default> create table t as values (1, 'one'), (2, 'two');
Time: 0.023s
default> select *
from t
where column1 > 1;
+---------+---------+
| column1 | column2 |
+---------+---------+
| 2       | two     |
+---------+---------+
Time: 0.024s
default> select column1 from t; …
```

Seafowl CLI initial implementation

---

docker-compose.yml
src/config/context.rs
src/config/schema.rs
src/context.rs
src/object_store/wrapped.rs
src/utils.rs
tests/statements/ddl.rs
tests/statements/dml.rs
tests/statements/mod.rs
tests/statements/vacuum.rs

This will allow configuring a specific path alongside a bucket where to store the data in.
Closes #470.

Support for sub-directories in object stores

---

src/catalog.rs
src/context/delta.rs
src/context/logical.rs
src/context/physical.rs
src/datafusion/parser.rs
src/nodes.rs
src/repository/default.rs
src/repository/interface.rs
src/repository/postgres.rs
src/repository/sqlite.rs
tests/statements/convert.rs
tests/statements/mod.rs

Convert a parquet table, as specified by a particular path, into a Delta table. Syntax closely follows that of [Databricks](https://docs.databricks.com/en/sql/language-manual/delta-convert-to-delta.html).
- The present implementation supports only in-place conversion, meaning that the Parquet table should be stored in a UUID dir inside the object store root (meaning bucket + any prefix).
- Note that delta-rs [doesn't support](https://github.com/delta-io/delta-rs/blob/733b5ffdde99cbfb256b8f69ae4529aeb1174599/crates/deltalake-core/src/operations/convert_to_delta.rs#L245-L248) appending/overwriting existing tables for now.
- This also lacks support for partitioned parquet tables—those could in principle be supported by extending the proposed syntax to allow passing the partitioning scheme, …

Convert to Delta table support

---

src/cli/mod.rs
src/config/context.rs
src/context/delta.rs
src/context/logical.rs
src/context/mod.rs
src/context/physical.rs
src/frontend/flight/handler.rs
src/frontend/flight/sql.rs
src/frontend/http.rs
tests/flight/client.rs
tests/flight/mod.rs
tests/flight/search_path.rs
tests/http/upload.rs

Closes #487 
Instead of adding a support for statement, enable equivalent functionality via tonic metadata values (gRPC request headers).

Implement a crude replacement for SET search_path in Flight SQL frontend

---

src/config/context.rs

This allows us to use envvars like `DATAFUSION_EXECUTION_BATCH_SIZE` to control various DataFusion parameters.

Use from_env when creating the session context

---

Cargo.lock
Cargo.toml
datafusion_remote_tables/Cargo.toml
src/context/delta.rs
src/context/logical.rs
src/context/mod.rs
src/context/physical.rs
src/datafusion/parser.rs
src/datafusion/utils.rs
src/frontend/http.rs
src/object_store/http.rs
src/provider.rs
src/testutils.rs
src/wasm_udf/mod.rs
src/wasm_udf/wasm.rs
tests/http/upload.rs
tests/statements/convert.rs
tests/statements/ddl.rs
tests/statements/dml.rs
tests/statements/mod.rs
tests/statements/time_travel.rs
tests/statements/vacuum.rs

Pick up a couple of fixes and features (timestamp-to-date, LIKE-operators, join cardinality panic).

Datafusion post-35 upgrade

---

docker-compose.yml
src/config/context.rs
src/config/schema.rs
src/object_store/wrapped.rs
tests/statements/ddl.rs
tests/statements/mod.rs

If the access_key/secret_key aren't set, skip signing the requests and treat the bucket as public.

Add support for public S3 buckets

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
clade/proto/schema.proto
docker-compose.yml
src/catalog/metastore.rs
src/catalog/mod.rs
src/catalog/repository.rs
src/config/context.rs
src/main.rs
src/object_store/wrapped.rs
src/provider.rs
tests/clade/mod.rs
tests/clade/query.rs
tests/fixtures.rs
tests/main.rs
tests/statements/ddl.rs
tests/statements/mod.rs

This enables metastore to setup delta tables with a different object store than the one configured in the toml file.
Currently does not support writes, due to metastore limitations.

Add support for dynamic object store usage via clade

---

src/catalog/repository.rs

Thus avoid returning same table for each column in the `SchemaStore::list` for repository-type metastores.

Fold all tables-columns into only tables when listing schemas

---

src/config/context.rs
src/config/schema.rs
src/context/mod.rs
tests/clade/mod.rs
tests/clade/query.rs

Conditional on using the Clade catalog, in which case it is internally set to use an in-memory store.

Make `object_store` confgi section optional

---

Cargo.lock
Cargo.toml
src/context/physical.rs
src/object_store/cache.rs

List of improvements:
- move out the writing of data to disk to a separate task
- and remove the lock on the file manager
- but let all the incoming calls for the requested range use the in-memory bytes until the write completes
- finally, change moka eviction policy to LRU
Tested on local minio using ClickBench q19, seems to improve against both old-cache and no-cache setups.

Improve caching object store performance

---

src/catalog/metastore.rs
tests/statements/query.rs

Also uncomment the remote table tests that now pass.

Fix condition for caching clade object stores

---

Cargo.lock
Cargo.toml
src/frontend/flight/mod.rs
src/frontend/http.rs
src/main.rs
tests/flight/mod.rs

This simplifies shutdown handling and means that if a subsystem fails to start (panics), Seafowl exits.
Tested manually (set flight port to an already-used one):
```
2024-04-11T12:26:00.638088Z  INFO main ThreadId(01) seafowl: Starting Seafowl 0.5.5
2024-04-11T12:26:00.638236Z  INFO main ThreadId(01) seafowl: Loading the configuration from seafowl.toml
2024-04-11T12:26:00.658400Z  INFO tokio-runtime-worker ThreadId(19) seafowl: Starting the Arrow Flight frontend on 127.0.0.1:9000
2024-04-11T12:26:00.658437Z  INFO tokio-runtime-worker ThreadId(15) seafowl: Starting the PostgreSQL frontend on 127.0.0.1:6432
2024-04-11T12:26:00.658486Z  WARN tokio-runtime-worker ThreadId(15) seafowl: The PostgreSQL frontend doesn't have authentication or encryption and should only be used in development! …
```

Use tokio-graceful-shutdown for SIGINT / SIGTERM

---

src/object_store/cache.rs

This is a naive implementation of https://github.com/splitgraph/seafowl/pull/514 (and therefore less complex), where we don't use synchronization to avoid request de-duplucation, but instead try do a best-effort chunk coalescing, and batch them into a single call.
Compared to current main, this implementation seems to be more stable, and doesn't experience the hanging in TPC-H q18 and q21, since it does not use any synchronization primitives.
As for perf, in the (idealized) no latency case it is on par with the current caching object store. However in more realistic scenarios of modest delays (15ms) it consistently outperforms it:

Best effort chunk coalescing implementation

---

src/catalog/metastore.rs
src/config/context.rs
src/context/physical.rs
src/object_store/factory.rs
src/object_store/mod.rs
src/object_store/wrapped.rs

The factory makes sure that object_store clients are only built once (using the URL and options as the key, no expiry) instead of on every call. This means that the cached data from the same object store will be shared across several queries and won't get reset.

Move Delta store creation into a separate ObjectStoreFactory

---

Cargo.lock
Cargo.toml
src/catalog/metastore.rs
src/config/context.rs
src/config/schema.rs
src/frontend/flight/mod.rs
src/frontend/http.rs
src/lib.rs
src/main.rs
src/memory_pool.rs
src/object_store/factory.rs
src/provider.rs
src/utils.rs

Make the metrics feature non-optional (there's a lot of code coming that exposes metrics and it'll get painful/pointless to maintain the ability to opt out of compiling metrics support at the cargo feature level
Add a special `MemoryPool` that wraps the default DataFusion `MemoryPool` (that setting defaults to `GreedyMemoryPool`, so construct that explicitly) and logs the total allocated/released bytes by each DataFusion query tree node.
Also replace all uses of `RwLock<HashMap>` to `DashMap` as @gruuya proposed.
Sample output:
```
seafowl_datafusion_memory_pool_reserved_bytes_current 0
seafowl_datafusion_memory_pool_freed_bytes_total{consumer="RepartitionExec"} 2033677121
seafowl_datafusion_memory_pool_freed_bytes_total{consumer="NestedLoopJoinLoad"} 15072 …
```

Add Prometheus metrics to MemoryManager

---

src/config/schema.rs
src/object_store/cache.rs
src/object_store/factory.rs

Add a bunch of various timing / sizing metrics to the object store cache:
- Bytes read from disk and from memory for cache hits
- Bytes written to disk
- Bytes requested in get_range for DataFusion
- Success/error rate of all outbound object store calls and time-to-first-byte
- Cache consistency "warnings" (our mitigations against race conditions)
Limitations:
- Doesn't instrument the sizes returned by non-get-range methods (those return streams and we don't wrap them in an instrumenting wrapper)
- Because of this, some timings on certain methods are meaningless (e.g. list seems to return almost immediately and only loads data when the stream is polled) and should potentially be removed
This is based on top of https://github.com/splitgraph/seafowl/pull/518/ which has some DataFusion …

Add various object store cache Prometheus metrics

---

Cargo.lock
Cargo.toml
clade/Cargo.toml
datafusion_remote_tables/Cargo.toml
datafusion_remote_tables/src/filter_pushdown.rs
src/context/delta.rs
src/context/logical.rs
src/context/physical.rs
src/datafusion/parser.rs
src/frontend/http.rs
src/provider.rs
src/system_tables.rs
src/wasm_udf/wasm.rs
tests/clade/query.rs
tests/flight/e2e.rs

Also bump Arrow to v51, and patch to pick up https://github.com/apache/datafusion/pull/10114,

DataFusion 37.1 upgrade

---

Cargo.lock
Cargo.toml
tests/statements/convert.rs
tests/statements/mod.rs

This so as to pick up the fix for decimal stats: https://github.com/delta-io/delta-rs/pull/2491

Point delta-rs to our fork

---

src/frontend/flight/sync.rs
tests/flight/mod.rs
tests/flight/sync.rs

This PR introduces:
- qualifier generation from record batches
- delta table partition file pruning
- applying sync data to build an input plan to stream through

Add support for deletes and updates that don't touch primary keys

---

src/frontend/flight/sync/metrics.rs
src/frontend/flight/sync/mod.rs
src/frontend/flight/sync/writer.rs

Add metrics tracking byte size/row count for:
- incoming request
- compaction
- flushing
as well as timings for the last two ops.

Add sync metrics

---

src/config/schema.rs
src/frontend/flight/handler.rs
src/frontend/flight/mod.rs
src/frontend/flight/sync/mod.rs
src/frontend/flight/sync/writer.rs
tests/flight/mod.rs
tests/flight/sync.rs

Try to flush on a regular interval, so as not to rely on sync calls to do the pushing.
Also:
- make `enqueue_sync` non-async by decoupling table creation and flushing from it
- make table creation lazy (done during actual flushing)
- explicit `flush` method is to be used by the handler

Add flush task

---

tests/main.rs

This PR makes the tests more robust against `ConnectionRefused` errors and ensure it retries the connection properly before panicking.
Changes Made:
- **Increased Retries:** Changed the retry count from 3 to 5.
- **Exponential backoff:** Instead of a fixed delay, now it uses a exponential backoff to gradually increase the wait time between retries. This can reduce the total wait time in successful cases while still allowing for enough time if the service is slow to start.
- **Logging:** Added tracing for better logging to capture more information about each connection attempt and errors encountered.

Increase retries and add delay backoff to connect to client on tests

---

.github/workflows/nightly.yml

- Allow the `nightly` workflow to be triggered manually
- Push branch builds to Dockerhub
- Allow branch builds to be referenced by other projects
- Trigger a workflow on this branch:
```
gh workflow run 'Build nightly binaries and perform releases' --ref SergeiPatiakin/workflow-dispatch
```
- Verify build is pushed to Dockerhub under the tag `commit-<sha>`

workflow_dispatch trigger for nightly workflow

---

src/main.rs

This is in line with the `env_logger` crate https://docs.rs/env_logger/latest/env_logger/#disabling-colors

Allow using `RUST_LOG_STYLE=never` to disable ANSI colors

---

Cargo.lock
Cargo.toml

Use our fork for now to pick up https://github.com/apache/datafusion/pull/11386 until (delta-rs and) we migrate to 40.0.0, when we can just patch from the upstream.

TPC-DS Q75 fix backport

---

clade/proto/schema.proto
src/catalog/metastore.rs
src/catalog/repository.rs
tests/fixtures.rs

As opposed to keying them via their root URL.

Use the storage location name as the key in the clade schema

---

Cargo.lock
Cargo.toml

This PR upgrades object_store dependency to 0.10.2 to add new functionality for BEAC-167

Upgrade object_store dependency to 0.10.2

---

src/config/schema.rs
src/frontend/flight/sync/writer.rs

This is to avoid the stack overflow during plan tree walking in optimizations/physical plan conversion etc.

Add criteria for max separate sync calls to apply when flushing

---

Cargo.lock
Cargo.toml
object_store_factory/Cargo.toml
object_store_factory/src/aws.rs
object_store_factory/src/google.rs
object_store_factory/src/lib.rs
object_store_factory/src/local.rs
src/config/context.rs
src/config/schema.rs
src/context/delta.rs
src/context/mod.rs
src/context/physical.rs
src/object_store/factory.rs
src/object_store/wrapped.rs
tests/statements/mod.rs

This PR moves the object store configuration structs into the new crate `object_store_factory`.

BEAC-167: Move object store configs to object_store_factory

---

Cargo.lock
Cargo.toml
src/config/schema.rs
src/frontend/flight/sync/writer.rs

Also disable all analyzer and optimizer rules, to avoid the stack overflow issue when applying a large number of sync calls during flushing.
Finally, make `DataSyncConfig::max_syncs_per_url` default to 100 now; it also works for 200 too but that incurs a performance penalty, so we should strive to get inter-sync dataframe squashing as a follow-up.

Patch DF to circumvent an analyzer rule

---

clade/proto/sync.proto
src/frontend/flight/handler.rs
src/frontend/flight/sync/metrics.rs
src/frontend/flight/sync/mod.rs
src/frontend/flight/sync/schema.rs
src/frontend/flight/sync/utils.rs
src/frontend/flight/sync/writer.rs
tests/flight/sync.rs
tests/flight/sync_fail.rs

Make sequence numbers optional in the protocol, and don't rely on their presence for the flushing mechanism to work. The reason for this is that PGD might not know the sequence number until the very end (last message) of the transaction.
This is achieved with a single queue of pending transactions, whereby with bookkeeping we:
1. track which txs are complete (as soon as they have `Some` sequence number)
2. track which txs have all tables/locations flushed out
3. make sure to mark a tx as durable only if all preceding txs are also durable

Optional sync sequence number

---

src/frontend/flight/handler.rs
src/frontend/flight/sql.rs
src/frontend/flight/sync/metrics.rs
src/frontend/flight/sync/schema.rs
src/frontend/flight/sync/utils.rs
src/frontend/flight/sync/writer.rs

This is to signal a transaction end.
Also rename batch compaction to squashing throughout.

Support empty syncs with no batches provided as payload

---

object_store_factory/src/aws.rs
src/datafusion/parser.rs

Remove the bucket from the key-value config as it is already expected the bucket to be in the URL.  The object store is uniquely determined by the URL + options).

Remove bucket from options

---

src/catalog/empty.rs
src/catalog/metastore.rs
src/catalog/mod.rs
src/config/context.rs
src/config/schema.rs
src/context/delta.rs
src/context/logical.rs
src/context/mod.rs
src/context/physical.rs
src/datafusion/parser.rs
src/frontend/flight/handler.rs
src/frontend/flight/sync/writer.rs
src/main.rs
src/object_store/factory.rs
src/utils.rs
tests/clade/mod.rs
tests/clade/query.rs
tests/fixtures.rs
tests/flight/client.rs
tests/flight/inline_metastore.rs
tests/flight/mod.rs
tests/flight/search_path.rs
tests/flight/sync.rs
tests/flight/sync_fail.rs
tests/statements/convert.rs
tests/statements/ddl.rs
tests/statements/vacuum.rs

In this case, Seafowl expects the metastore and the object store settings to be passed to it over the Flight RPC endpoint (when querying or writing) and will error out otherwise.
This required some weird refactoring because so many things assume there is a "default" object store and a metastore, so all SeafowlContext methods that want to access the internal default object store for writes now do it through a method that errors out if it's not set up. For the metastore, this change defines an EmptyMetastore that errors if Seafowl actually tries to use it.

Allow running Seafowl without an object store / catalog config.

---

Cargo.lock
Cargo.toml
src/context/delta.rs
src/frontend/flight/sync/utils.rs
src/frontend/flight/sync/writer.rs
src/frontend/http.rs

This removes one pathological scenario, and that is when the changeset contains very small old pks and very large new pks (or vice-versa), such that the whole range basically encompasses all partition files, so we end up re-writing everything.
In addition it fixes a bug whereby the sync base scan does both partition and row pruning, but the former is inclusive (which we want) while the later is exclusive (which we don't). The fix is to use [a new API](https://github.com/splitgraph/delta-rs/commit/98fa4cc99a7a84c482082baf942e6a29797639d0) for creating a Delta `TableProvider` based on a particular set of files, which can then be converted to `TableSource` to be used in logical planning.

Separate qualifier for new and old sync pks

---

Cargo.lock
Cargo.toml
object_store_factory/src/aws.rs
src/frontend/flight/sync/writer.rs
src/object_store/wrapped.rs

Instead of the previous one which is empty for adds obtained via `DeltaTableState::file_actions`, use the from https://github.com/delta-io/delta-rs/pull/2822.
This allows us to trigger the fine-grained pruning routine.

Use the new public method for getting Add stats from the logs

---

src/context/logical.rs
src/context/physical.rs
src/datafusion/parser.rs
src/nodes.rs
tests/statements/mod.rs
tests/statements/truncate.rs

- Add support for `TRUNCATE TABLE x`
- This is equivalent to `DELETE FROM x`, but it also works with inline metastore
- Skip updating `table_versions` to ensure it works with inline metastore

Add support for TRUNCATE command

---

clade/build.rs
src/frontend/flight/sync/schema.rs
src/frontend/flight/sync/utils.rs
src/frontend/flight/sync/writer.rs
tests/flight/sync_fail.rs

Implement logical inter-sync squashing during flushing in the `SeafowlDataSyncWriter`, such that the resulting stream is the equivalent combined/total sync batch to be applied to the base scan.
Instead of starting of with a base scan of parquet files to re-write, and applying each sync batch iteratively on top of it, flip it around and first do logical squashing of sync batches and only then do a single join with the base scan.
- This greatly improves the efficiency of the plan execution and therefore writes at the expense of code complexity. 
- The perf improvement is especially pronounced in case of UPDATEs that touch many partition files, since we avoid doing K joins for N base rows when applying each sync. 
- Instead we have only 1 join with N base rows, whereas the sync joins grow in …

Logical inter-sync squashing

---

src/frontend/flight/handler.rs
src/frontend/flight/mod.rs
src/frontend/flight/sql.rs
src/lib.rs
src/sync/metrics.rs
src/sync/mod.rs
src/sync/schema.rs
src/sync/utils.rs
src/sync/writer.rs

To make the lookups during logical sync squashing faster pre-index the sync schema columns by role and name.
Also do `git mv src/frontend/flight/sync/* src/sync`.

Index sync columns

---

src/repository/default.rs

There is a bug on SQLite driver, which makes it return a result before the actual commit.
When using `fetch_one()` for queries with a RETURNING clause, the query prematurely returns after fetching the first result row without ensuring the SQLite statement is fully completed.
This bug was causing the test `test_sqlite_repository_read_only()` to fail sometimes when creating a database at https://github.com/splitgraph/seafowl/blob/8a47781f82ad54c445940f0d2c9e1008d6ddc2fa/src/repository/default.rs#L142-L143. 
In this PR, I implement a workaround by manually starting a transaction before running the query and committing it afterwards.
Flaky failure example: 
https://github.com/splitgraph/seafowl/actions/runs/10721496337/job/29730146388

Fix flaky. Workaround for SQLite driver bug returning a result before the commit.

---

src/sync/schema/mod.rs
src/sync/utils.rs
src/sync/writer.rs

Add a test util to convert arrow to sync schema w/o explicit column descriptors, making the tests a lot less verbose.

Sync test polish

---

Cargo.lock
Cargo.toml
src/context/delta.rs
src/frontend/flight/handler.rs
src/frontend/flight/sql.rs
src/sync/metrics.rs
src/sync/planner.rs
src/sync/schema/join.rs
src/sync/schema/merge.rs
src/sync/schema/mod.rs
src/sync/utils.rs
src/sync/writer.rs
tests/flight/sync.rs

To make replication robust in the face of failures and crashes we need to be able to apply the same messages multiple times without the state deviating from the expected one. This should hold in general, i.e. for INSERTs, DELETEs, and UPDATEs (whether they change the PK or not).
Split up PK-changing UPDATEs into DELETEs + INSERTs, which makes them idempotent, assuming all columns (TOASTed or not) are supplied for such cases (since otherwise the INSERT has no idea where to pull the old values from).
Ultimately this is the fastest method method to get only-once semantics working, with alternatives such as aggregation/grouping/distinct-on etc. being much slower.

Make replication idempotent against commited rows

---

Cargo.lock
Cargo.toml
build.rs
src/frontend/flight/handler.rs
src/main.rs
src/object_store/http.rs

The signature is slightly changed and goes from
```
Seafowl v0.5.5-311-g4eaf0be (4eaf0bee53eb42a8401d3e791356c5a5b2061c78 2024-09-16T15:14:22Z)
Built by rustc 1.83.0-nightly on aarch64-apple-darwin at 2024-09-18T15:16:25.255082Z
Target: release aarch64-apple-darwin
Features: catalog_postgres,convergence,convergence_arrow,default,frontend_arrow_flight,frontend_postgres,remote_tables
```
to
```
Seafowl v0.5.5-311-g4eaf0be (4eaf0be 2024-09-16T17:14:22.000000000+02:00)
Built by rustc 1.83.0-nightly on aarch64-apple-darwin at 2024-09-19T12:42:57.988564000Z
Target: aarch64-apple-darwin
Opt level: 0
Features: catalog_postgres,convergence,convergence_arrow,default,frontend_arrow_flight,frontend_postgres,remote_tables
```
The `VERGEN_CARGO_PROFILE` var is no longer available, and the …

Replace the old vergen crate with a newer version

---

ci/clippy.sh
src/config/schema.rs
src/object_store/factory.rs
src/repository/default.rs
src/wasm_udf/data_types.rs
tests/fixtures.rs
tests/flight/inline_metastore.rs
tests/main.rs

Append the table path to the pre-existing url path instead of replacing it.

Fix prefix swallowing when creating the object store

---

docker-compose.yml
src/config/schema.rs
src/sync/planner.rs
src/sync/schema/mod.rs
src/sync/utils.rs
src/sync/writer.rs
tests/flight/mod.rs
tests/flight/sync.rs

Coalesce sync batches when enqueuing them. This ensures we stay below the `max_syncs_per_url` for longer, ultimately enabling us to accumulate/dump more rows per flush.
When enqueuing sync batches, if they share the same schema as a previous entry just append them to it, instead of creating a new entry.
Whereas the existing implementation has been optimized for a high volume/saturating use case, this is not the case for the opposite, i.e. batches with a low number of rows. Consequently this leads to poor throughput rates, and ultimately slows down the transaction processing speed for the entire cluster.

Sync batch coalescing

---

object_store_factory/src/lib.rs
src/object_store/factory.rs

Add prefixing logic for S3 and GCP object stores in object_store_factory::build_object_store_from_opts. This makes prefixing consistent across all object store types.

Handle prefixes for AmazonS3 and GoogleCloudStorage object stores

---

src/object_store/factory.rs
tests/fixtures.rs
tests/flight/mod.rs
tests/flight/sync.rs

The root storage location should always exist, and if it doesn't it'll error out with `Unable to canonicalize filesystem root`.
The additional table path should be wired in by a separate prefix store.

Make sure that local FS url points only to the root storage location

---

src/sync/schema/mod.rs
src/sync/utils.rs
src/sync/writer.rs

This prevents arrow `Column 'x' is declared as non-nullable but contains null values` errors during record batch creation.

Align batch schema nullability during squashing

---

Cargo.lock
Cargo.toml
src/context/delta.rs
src/context/mod.rs
src/context/physical.rs
src/sync/writer.rs

- Add enum LakehouseTableProvider that has variants for delta and iceberg
- Add method SeafowlContext::get_lakehouse_table_provider. To add iceberg support, methods from `physical.rs` in future PRs can:
- call this instead of SeafowlContext::try_get_delta_table
- implement separate logic for delta and iceberg variants of the table provider

Prepare for Iceberg support

---

Cargo.lock
Cargo.toml
docker-compose.yml
src/object_store/utils.rs
tests/clade/query.rs
tests/fixtures.rs
tests/flight/inline_metastore.rs
tests/statements/mod.rs

Adds conversion from object_store's `AmazonS3ConfigKey::SkipSignature` to new iceberg-rust S3 props that enable opendal anonymous access.

Add support for querying public Iceberg tables

---

clade/proto/sync.proto
src/frontend/flight/handler.rs
src/sync/mod.rs
tests/flight/sync.rs
tests/flight/sync_fail.rs

Prepare for Iceberg sync support:
- Add table format field to DataSyncCommand (can be Delta or Iceberg)
- For now, require the format to be Delta

Add format field to DataSyncCommand

---

src/context/iceberg.rs

This PR ports lakehouse-loader code from https://github.com/splitgraph/lakehouse-loader/pull/17 to increase compatibility with existing Iceberg tables

Allow immaterial schema differences for Iceberg append

---

src/frontend/flight/handler.rs
src/sync/mod.rs
src/sync/planner.rs
src/sync/writer.rs

This PR generalizes sync-related code from Delta-specific types towards a more abstract "sync target" type which can be Delta or Iceberg. We do not yet implement Iceberg sync functionality, that will be in a future PR.

Prepare for Iceberg Sync
