- src/config/schema.rs
- src/context.rs
- src/frontend/http.rs
- src/provider.rs
- src/repository/interface.rs
- src/wasm_udf/data_types.rs
- tests/end_to_end.rs
Minor things I discovered / had to change while writing the docs.
> Various small fixes

- src/catalog.rs
- src/context.rs
- src/nodes.rs
- src/repository/default.rs
- src/repository/interface.rs
- tests/end_to_end.rs
Fixes https://github.com/splitgraph/seafowl/issues/15
Fixes https://github.com/splitgraph/seafowl/issues/13
> Implement remaining DDL functions

- examples/multinode/README.md
- examples/multinode/configs/nginx/nginx.conf
- examples/multinode/configs/seafowl/seafowl.toml
- examples/multinode/docker-compose.yml
- examples/multinode/seafowl/Dockerfile
> Add example of running Seafowl with Minio/PG

- src/main.rs
- Don't import `unix::signal` on Windows (no SIGTERM there),
only wait for a Ctrl+c
- Rearrange the code so that the task that listens for an exit signal isn't
blocked on by the main thread. Instead, make it another task and `join_all`
in main on everything instead. This is so that panics on startup of one of
the tasks (e.g. port already taken) cause the program to crash too.
> Fix `SIGTERM/SIGINT` handling

- Cargo.lock
- Cargo.toml
- seafowl.toml
- src/remote_tables.rs
- tests/statements/query.rs
Bump connector-x to patch that converts PG JSON type to strings, and add tests.
> Add remote table json support

- src/catalog.rs
- src/repository/default.rs
- src/repository/interface.rs
- src/repository/postgres.rs
- src/repository/sqlite.rs
- src/system_tables.rs
- src/version.rs
- tests/statements/dml.rs
- tests/statements/query.rs
Add another system table for listing table partitions used for all table versions.
> Implement table_partitions system table

- .github/workflows/ci.yml
- src/remote_tables/pushdown_visitor.rs
Add pushdown of boolean filter expressions as well as the in-list expression.
> Extend filter expression pushdown surface area

- src/remote_tables/pushdown_visitor.rs
Convert other timestamp types when doing filter pushdown.
> Remote table timestamp filter extension

- datafusion_remote_tables/src/filter_pushdown.rs
Rename:
- `FilterPushdownVisitor` trait to `FilterPushdownConverter`
- `FilterPushdown` struct to `FilterPushdownVisitor`
> Alter naming in the remote table crate to something less misleading

- Cargo.lock
- Cargo.toml
- datafusion_remote_tables/Cargo.toml
- src/context.rs
- src/wasm_udf/wasm.rs
- tests/statements/mod.rs
- tests/statements/query.rs
- tests/statements/vacuum.rs
Bump dependencies and fix tests.
> Bump to Datafusion 18.0.0

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- docker-compose.yml
- src/object_store/wrapped.rs
- tests/statements/ddl.rs
- tests/statements/dml.rs
- tests/statements/mod.rs
- tests/statements/vacuum.rs
In addition extend integration tests object store parametrization with a S3 Minio-backed server. Closes #330
> Fix unimplemented method in AWS object store

- src/datafusion/utils.rs
- src/wasm_udf/data_types.rs
This pull request fixes some small typos.
> Fix some typos

- Cargo.toml
- src/context.rs
- src/frontend/http.rs
- src/frontend/http_utils.rs
- src/repository/default.rs
- tests/statements/query.rs
- tests/statements/query_legacy.rs
Make some errors more explicit and add some tests
> Fix a couple of unrelated leftover TODOs

- README.md
- tests/README.md
Just a few small steps I had to figure out recently, hopefully helps future contributors save some time.
> Add some explanatory text intended to help contributors run tests

- Cargo.lock
- Cargo.toml
- datafusion_remote_tables/Cargo.toml
- src/context.rs
- src/datafusion/parser.rs
- src/delta_rs/backports.rs
> Upgrade to DataFusion 24

- Cargo.lock
- Cargo.toml
- datafusion_remote_tables/Cargo.toml
- datafusion_remote_tables/src/provider.rs
- src/provider.rs
- tests/statements/mod.rs
- tests/statements/query.rs
Also upgrade Arrow to 43 and sqlx to 0.7.1.
> chore: DataFusion 28 upgrade

- seafowl.toml
- src/catalog.rs
- src/context.rs
- src/nodes.rs
- src/repository/default.rs
- src/repository/interface.rs
> Support DROP FUNCTION

- .github/workflows/nightly.yml
- Cargo.lock
- Cargo.toml
- datafusion_remote_tables/Cargo.toml
- src/context.rs
- src/delta_rs/backports.rs
- src/frontend/http.rs
- src/version.rs
- tests/statements/dml.rs
> chore: DataFusion 30 upgrade

- src/context.rs
- src/datafusion/parser.rs
- tests/statements/dml.rs
Also align with other DML statements and execute it eagerly inside `create_physical_plan`.
> Wire up COPY TO statement

- clade/build.rs
- clade/src/lib.rs
- tests/clade/mod.rs
Add the descriptor file to enable the grpc reflection service
> Expose reflection metadata

- Cargo.lock
- Cargo.toml
- src/config/context.rs
- src/frontend/flight/handler.rs
- src/frontend/flight/metrics.rs
- src/frontend/flight/mod.rs
- src/frontend/flight/sql.rs
- tests/cli/mod.rs
- tests/flight/client.rs
- tests/flight/mod.rs
- tests/flight/search_path.rs
- tests/http/mod.rs
- tests/http/query.rs
- tests/main.rs
Add basic gRPC metrics (path + status), via a middleware layer intercepting request/response.
> Add gRPC metrics

- docker-compose.yml
- src/frontend/flight/handler.rs
- src/frontend/flight/metrics.rs
- src/frontend/flight/sql.rs
Log query ids, request metadata as well as errors.
> Improve Arrow Flight SQL interface logging

- src/catalog/metastore.rs
- src/object_store/factory.rs
If we get an S3 object store through clade without a bucket or a custom endpoint, use the `resolve_bucket_region` function to find out where the bucket is (otherwise, we'll default to us-east-1).
> Autodetect bucket region in S3 without custom endpoints

- Cargo.lock
- Cargo.toml
- datafusion_remote_tables/Cargo.toml
- datafusion_remote_tables/src/factory.rs
- datafusion_remote_tables/src/filter_pushdown.rs
- src/config/schema.rs
- src/context/delta.rs
- src/context/logical.rs
- src/context/mod.rs
- src/context/physical.rs
- src/datafusion/parser.rs
- src/frontend/flight/sync/writer.rs
- src/frontend/http.rs
- src/nodes.rs
- src/object_store/cache.rs
- src/object_store/http.rs
- src/object_store/wrapped.rs
- src/version.rs
- tests/statements/query.rs
> Upgrade to DataFusion 39

- Cargo.lock
- Cargo.toml
Pick up https://github.com/delta-io/delta-rs/pull/2604
> Bump delta-rs

- .github/workflows/ci.yml
- clade/proto/sync.proto
- src/frontend/flight/handler.rs
- src/frontend/flight/sync/utils.rs
- src/frontend/flight/sync/writer.rs
- tests/flight/sync.rs
- tests/flight/sync_fail.rs
- tests/http/upload.rs
Vadim and Petr have suggested another value I use that will be a string. Since I'm the one that dissuaded us from doing that in the first place, I have offered up a partial attempt at reverting this to what Marko originally implemented.
I have some questions about the tests though. I'm also not sure how to build the protos? I can't see how we do that in CI or anything.
> Make origin a string

- object_store_factory/src/aws.rs
- tests/fixtures.rs
This PR fixes a problem introduced on a previous commit that was breaking some tests.
> Remove prefix from options

- .github/workflows/ci.yml
as per https://github.com/splitgraph/seafowl/pull/642#issuecomment-2325778457
> Run workflows on PRs as well

- object_store_factory/src/local.rs
- src/config/schema.rs
- src/context/delta.rs
- src/main.rs
- src/object_store/wrapped.rs
See https://github.com/splitgraph/seafowl/pull/642, just fixing the formatting so CI can run
> Add PR 642 from @mrchypark

- .github/workflows/ci.yml
- src/sync/metrics.rs
- src/sync/mod.rs
- src/sync/planner.rs
- src/sync/schema/join.rs
- src/sync/schema/merge.rs
- src/sync/writer.rs
No (major) new things added here, just helping with code readability a bit.
The only extra thing is the planning time metric.
> Extract the sync planning logic into a separate module

- Cargo.lock
- Cargo.toml
- src/frontend/flight/handler.rs
- src/sync/planner.rs
- src/sync/utils.rs
- src/sync/writer.rs
- Various outputs as the sync progresses
- Add the `backtrace` feature to DataFusion (https://datafusion.apache.org/user-guide/crate-configuration.html#enable-backtraces)
> Add more various debug output

- src/config/schema.rs
This requires the users to override them explicitly by generating a password manually.
> Disable writes in the deafult config file

- Cargo.lock
- Cargo.toml
- src/sync/planner.rs
- src/sync/writer.rs
This fixes some decimal parsing issues.
> Pick up backport of arrow-rs PR 6729

- object_store_factory/src/aws.rs
- Fix bug on region detection logic.
> Improve region detection logic on object store factory

- Cargo.lock
- Cargo.toml
Use Splitgraph fork of iceberg-rust
> Use iceberg-rust fork

- Cargo.lock
- Cargo.toml
Also bump deltalake to main branch with merged stats fix pr.
> Bump Iceberg to pick up DataFusion fix

- Cargo.lock
- Cargo.toml
- object_store_factory/Cargo.toml
- object_store_factory/src/lib.rs
- object_store_factory/src/utils.rs
- src/catalog/metastore.rs
- src/object_store/utils.rs
This makes it useful beyond just Seafowl.
> Move FileIO props conversion into the object_store_factory

- Cargo.lock
- Cargo.toml
- src/context/iceberg.rs
Pick up https://github.com/apache/iceberg-rust/pull/829
> Bump Iceberg to pick up fix for plan and stream schema mismatch
